name: cicd
on: [push]
jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: main

      - uses: actions/setup-java@v1
        with:
          java-version: '11' # The JDK version to make available on the path.
          java-package: jdk # (jre, jdk, or jdk+fx) - defaults to jdk
          architecture: x64 # (x64 or x86) - defaults to x64

      - name: run tests
        run: ./mvnw clean test

  code-quality:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          ref: main

      - uses: actions/setup-java@v1
        with:
          java-version: '11' # The JDK version to make available on the path.
          java-package: jdk # (jre, jdk, or jdk+fx) - defaults to jdk
          architecture: x64 # (x64 or x86) - defaults to x64

      - name: run code quality checks
        env:
          GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: mvn verify sonar:sonar

  package:
    runs-on: ubuntu-latest
    needs: [code-quality, tests]
    steps:
      - uses: actions/checkout@v2
        with:
          ref: main

      - uses: actions/setup-java@v1
        with:
          java-version: '11' # The JDK version to make available on the path.
          java-package: jdk # (jre, jdk, or jdk+fx) - defaults to jdk
          architecture: x64 # (x64 or x86) - defaults to x64

      - name: build with gradle
        run: ./mvnw clean test package

      - name: get artifact version
        id: image_version_step
        run: echo "::set-output name=ARTIFACT_VERSION::$(./mvnw help:evaluate -Dexpression=project.version | egrep -v '(^\[|Download\w+:)')"

      - name: upload artifact
        uses: actions/upload-artifact@v2
        with:
          name: bigly-outputter-latest
          path: ./target/bigly-outputter*.jar

      - name: build docker image
        run: ./mvnw clean spring-boot:build-image

      - name: tag docker images
        run: |
          docker tag bigly-outputter:${{ steps.image_version_step.outputs.ARTIFACT_VERSION }} generalmeow/bigly-outputter:${{ steps.image_version_step.outputs.ARTIFACT_VERSION }}
          docker tag bigly-outputter:${{ steps.image_version_step.outputs.ARTIFACT_VERSION }} generalmeow/bigly-outputter:latest

      - name: scan
        uses: anchore/scan-action@v2
        with:
          image: "generalmeow/bigly-outputter:latest"
#          fail-build: true
#          severity-cutoff: critical

      - name: docker login
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: upload docker image
        run: |
          docker push generalmeow/bigly-outputter:${{ steps.image_version_step.outputs.ARTIFACT_VERSION }}
          docker push generalmeow/bigly-outputter:latest
